In [1]:
import tensorflow as tf
import numpy as np
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping

Using TensorFlow backend.


In [2]:
import cv2

In [3]:
# capture the video
capture = cv2.VideoCapture('./videoplayback.3gpp')

In [4]:
frameCount = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
frameWidth = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
frameHeight = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))

print(frameCount)
print(frameHeight)
print(frameWidth)


1081
240
240


In [5]:
# frames = np.memmap(filename='frames_as',dtype='int64', mode='w+',
#               shape=(frameCount, frameWidth, frameHeight, 3))
frames = np.empty((frameCount, frameWidth, frameHeight, 3), np.dtype('uint8'))
print(frames.shape)

(1081, 240, 240, 3)


In [6]:
frames[9, :, :, :].shape

(240, 240, 3)

In [7]:
index = 0
ret = True
while (index < frameCount and ret):
    ret, frame = capture.read()
    print(frame)
    frames[index, :, :, :] = frame
    index += 1

[[[29 31 38]
  [52 54 61]
  [60 62 69]
  ..., 
  [43 43 43]
  [47 47 47]
  [51 51 51]]

 [[36 38 45]
  [48 50 57]
  [55 57 64]
  ..., 
  [41 41 41]
  [46 46 46]
  [50 50 50]]

 [[47 49 56]
  [43 45 52]
  [49 51 58]
  ..., 
  [39 39 39]
  [43 43 43]
  [46 46 46]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [18 15 16]
  [18 15 16]
  [18 15 16]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [18 15 16]
  [18 15 16]
  [18 15 16]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [18 15 16]
  [18 15 16]
  [18 15 16]]]
[[[29 31 38]
  [40 42 49]
  [55 57 64]
  ..., 
  [43 43 43]
  [47 47 47]
  [51 51 51]]

 [[36 38 45]
  [42 44 51]
  [52 54 61]
  ..., 
  [41 41 41]
  [46 46 46]
  [50 50 50]]

 [[47 49 56]
  [45 47 54]
  [46 48 55]
  ..., 
  [39 39 39]
  [43 43 43]
  [46 46 46]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [18 15 16]
  [18 15 16]
  [18 15 16]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [18 15 16]
  [18 15 16]
  [18 15 16]]

 [[38 35 34]
  [38

[[[50 52 59]
  [41 43 50]
  [47 49 56]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 [[45 47 54]
  [41 43 50]
  [53 55 62]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 [[36 38 45]
  [42 44 51]
  [59 61 68]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 ..., 
 [[15 12 11]
  [15 12 11]
  [15 12 11]
  ..., 
  [39 36 37]
  [36 33 34]
  [31 28 29]]

 [[14 11 10]
  [14 11 10]
  [14 11 10]
  ..., 
  [39 36 37]
  [36 33 34]
  [31 28 29]]

 [[14 11 10]
  [14 11 10]
  [14 11 10]
  ..., 
  [39 36 37]
  [36 33 34]
  [31 28 29]]]
[[[47 49 56]
  [52 54 61]
  [50 52 59]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 [[52 54 61]
  [54 56 63]
  [48 50 57]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 [[56 58 65]
  [54 56 63]
  [45 47 54]
  ..., 
  [33 33 33]
  [32 32 32]
  [32 32 32]]

 ..., 
 [[15 12 11]
  [15 12 11]
  [15 12 11]
  ..., 
  [39 36 37]
  [36 33 34]
  [31 28 29]]

 [[14 11 10]
  [14 11 10]
  [14 11 10]
  ..., 
  [39 36 37]
  [36 33 34]
  [31 28 29]]

 [[14 11 10]
  [14

[[[ 71  74  79]
  [ 86  89  94]
  [ 97 100 105]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 59  62  67]
  [ 75  78  83]
  [ 91  94  99]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 57  60  65]
  [ 69  72  77]
  [ 83  86  91]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 ..., 
 [[ 18  17  19]
  [ 18  17  19]
  [ 18  17  19]
  ..., 
  [ 35  31  34]
  [ 35  31  34]
  [ 35  31  34]]

 [[ 15  14  16]
  [ 15  14  16]
  [ 15  14  16]
  ..., 
  [ 34  30  33]
  [ 34  30  33]
  [ 34  30  33]]

 [[ 12  11  13]
  [ 12  11  13]
  [ 12  11  13]
  ..., 
  [ 33  29  32]
  [ 33  29  32]
  [ 33  29  32]]]
[[[ 73  76  81]
  [ 88  91  96]
  [ 95  98 103]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 64  67  72]
  [ 80  83  88]
  [ 91  94  99]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 66  69  74]
  [ 76  79  84]
  [ 84  87  92]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 ..., 
 [[ 18  17  19]
  [ 18  17  19]


  [ 33  33  33]]]
[[[103 106 111]
  [ 88  91  96]
  [ 82  85  90]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 [[ 92  95 100]
  [ 92  95 100]
  [ 89  92  97]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 [[ 78  81  86]
  [ 92  95 100]
  [ 95  98 103]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 ..., 
 [[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 25  25  25]
  [ 25  25  25]
  [ 25  25  25]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]]
[[[103 106 111]
  [ 88  91  96]
  [ 82  85  90]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 [[ 92  95 100]
  [ 92  95 100]
  [ 89  92  97]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 [[ 78  81  86]
  [ 92  95 100]
  [ 95  98 103]
  ..., 
  [ 38  37  39]
  [ 38  37  39]
  [ 46  45  47]]

 ..., 
 [[ 25  25  25

[[[71 74 79]
  [73 76 81]
  [71 74 79]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 [[78 81 86]
  [78 81 86]
  [76 79 84]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 [[90 93 98]
  [88 91 96]
  [84 87 92]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 ..., 
 [[34 34 32]
  [34 34 32]
  [33 33 31]
  ..., 
  [33 33 33]
  [33 33 33]
  [33 33 33]]

 [[31 31 31]
  [31 31 31]
  [31 31 31]
  ..., 
  [33 33 33]
  [33 33 33]
  [33 33 33]]

 [[29 29 29]
  [29 29 29]
  [29 29 29]
  ..., 
  [33 33 33]
  [33 33 33]
  [33 33 33]]]
[[[63 66 71]
  [64 67 72]
  [68 71 76]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 [[67 70 75]
  [68 71 76]
  [70 73 78]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 [[76 79 84]
  [77 80 85]
  [78 81 86]
  ..., 
  [41 40 42]
  [38 37 39]
  [44 43 45]]

 ..., 
 [[34 34 32]
  [34 34 32]
  [34 34 32]
  ..., 
  [33 33 33]
  [33 33 33]
  [33 33 33]]

 [[31 31 31]
  [31 31 31]
  [31 31 31]
  ..., 
  [33 33 33]
  [33 33 33]
  [33 33 33]]

 [[29 29 29]
  [29

[[[58 59 64]
  [55 56 61]
  [50 51 56]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 [[59 60 65]
  [57 58 63]
  [52 53 58]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 [[64 65 70]
  [63 64 69]
  [59 60 65]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 ..., 
 [[33 30 31]
  [33 30 31]
  [33 30 31]
  ..., 
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 29 30]
  [32 29 30]
  [32 29 30]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[32 29 30]
  [32 29 30]
  [32 29 30]
  ..., 
  [30 30 30]
  [30 30 30]
  [30 30 30]]]
[[[58 59 64]
  [55 56 61]
  [50 51 56]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 [[59 60 65]
  [56 57 62]
  [51 52 57]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 [[62 63 68]
  [61 62 67]
  [56 57 62]
  ..., 
  [40 37 38]
  [39 36 37]
  [38 35 36]]

 ..., 
 [[33 30 31]
  [33 30 31]
  [33 30 31]
  ..., 
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 29 30]
  [32 29 30]
  [32 29 30]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[32 29 30]
  [32

  [31 31 31]]]
[[[71 72 77]
  [63 64 69]
  [64 65 70]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 [[71 72 77]
  [63 64 69]
  [64 65 70]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 [[70 71 76]
  [64 65 70]
  [65 66 71]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 ..., 
 [[21 22 32]
  [21 22 32]
  [21 22 32]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[21 22 32]
  [21 22 32]
  [21 22 32]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[21 22 32]
  [21 22 32]
  [21 22 32]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]]
[[[59 60 65]
  [55 56 61]
  [51 52 57]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 [[59 60 65]
  [55 56 61]
  [51 52 57]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 [[62 63 68]
  [57 58 63]
  [54 55 60]
  ..., 
  [35 32 31]
  [34 31 30]
  [36 33 32]]

 ..., 
 [[15 16 26]
  [15 16 26]
  [15 16 26]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[15 16 26]
  [15 16 26]
  [15 16 26]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[

  [ 31  31  31]]]
[[[82 83 88]
  [88 89 94]
  [91 92 97]
  ..., 
  [39 36 35]
  [39 36 35]
  [40 37 36]]

 [[76 77 82]
  [85 86 91]
  [93 94 99]
  ..., 
  [39 36 35]
  [39 36 35]
  [40 37 36]]

 [[66 67 72]
  [77 78 83]
  [91 92 97]
  ..., 
  [39 36 35]
  [39 36 35]
  [40 37 36]]

 ..., 
 [[33 33 33]
  [34 34 34]
  [34 34 34]
  ..., 
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[32 32 32]
  [33 33 33]
  [33 33 33]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[33 33 33]
  [33 33 33]
  [33 33 33]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]]
[[[ 90  91  96]
  [ 95  96 101]
  [ 95  96 101]
  ..., 
  [ 39  36  35]
  [ 39  36  35]
  [ 40  37  36]]

 [[ 83  84  89]
  [ 91  92  97]
  [ 97  98 103]
  ..., 
  [ 39  36  35]
  [ 39  36  35]
  [ 40  37  36]]

 [[ 71  72  77]
  [ 80  81  86]
  [ 93  94  99]
  ..., 
  [ 39  36  35]
  [ 39  36  35]
  [ 40  37  36]]

 ..., 
 [[ 33  33  33]
  [ 34  34  34]
  [ 34  34  34]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 32  32  32]


[[[ 68  70  77]
  [ 70  72  79]
  [ 71  73  80]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 81  83  90]
  [ 84  86  93]
  [ 80  82  89]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 86  88  95]
  [ 92  94 101]
  [ 88  90  97]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 ..., 
 [[ 33  34  39]
  [ 33  34  39]
  [ 31  32  37]
  ..., 
  [ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]]

 [[ 31  32  37]
  [ 31  32  37]
  [ 30  31  36]
  ..., 
  [ 31  31  31]
  [ 31  31  31]
  [ 31  31  31]]

 [[ 30  31  36]
  [ 30  31  36]
  [ 29  30  35]
  ..., 
  [ 30  30  30]
  [ 30  30  30]
  [ 30  30  30]]]
[[[ 74  76  83]
  [ 77  79  86]
  [ 75  77  84]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 83  85  92]
  [ 88  90  97]
  [ 83  85  92]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 [[ 85  87  94]
  [ 92  94 101]
  [ 90  92  99]
  ..., 
  [ 37  37  37]
  [ 37  37  37]
  [ 37  37  37]]

 ..., 
 [[ 33  34  39]
  [ 31  32  37]


  [19 19 19]]]
[[[63 66 71]
  [64 67 72]
  [62 65 70]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 [[71 74 79]
  [71 74 79]
  [68 71 76]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 [[81 84 89]
  [81 84 89]
  [76 79 84]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 ..., 
 [[35 32 31]
  [35 32 31]
  [35 32 31]
  ..., 
  [17 17 17]
  [11 11 11]
  [10 10 10]]

 [[34 31 30]
  [34 31 30]
  [34 31 30]
  ..., 
  [16 16 16]
  [10 10 10]
  [ 9  9  9]]

 [[34 31 30]
  [34 31 30]
  [34 31 30]
  ..., 
  [16 16 16]
  [10 10 10]
  [ 9  9  9]]]
[[[63 66 71]
  [64 67 72]
  [63 66 71]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 [[68 71 76]
  [68 71 76]
  [67 70 75]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 [[76 79 84]
  [76 79 84]
  [74 77 82]
  ..., 
  [40 37 38]
  [38 35 36]
  [38 35 36]]

 ..., 
 [[35 32 31]
  [35 32 31]
  [35 32 31]
  ..., 
  [11 11 11]
  [10 10 10]
  [10 10 10]]

 [[34 31 30]
  [34 31 30]
  [34 31 30]
  ..., 
  [10 10 10]
  [ 9  9  9]
  [ 9  9  9]]

 [[

  [29 25 28]]]
[[[77 80 85]
  [76 79 84]
  [75 78 83]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 [[77 80 85]
  [76 79 84]
  [75 78 83]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 [[68 71 76]
  [68 71 76]
  [67 70 75]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 ..., 
 [[38 35 36]
  [38 35 36]
  [38 35 36]
  ..., 
  [24 20 23]
  [27 23 26]
  [29 25 28]]

 [[36 33 34]
  [36 33 34]
  [36 33 34]
  ..., 
  [24 20 23]
  [27 23 26]
  [29 25 28]]

 [[35 32 33]
  [35 32 33]
  [35 32 33]
  ..., 
  [24 20 23]
  [27 23 26]
  [29 25 28]]]
[[[77 80 85]
  [77 80 85]
  [76 79 84]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 [[77 80 85]
  [77 80 85]
  [76 79 84]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 [[77 80 85]
  [77 80 85]
  [76 79 84]
  ..., 
  [39 36 37]
  [38 35 36]
  [36 33 34]]

 ..., 
 [[38 35 36]
  [38 35 36]
  [38 35 36]
  ..., 
  [24 20 23]
  [27 23 26]
  [29 25 28]]

 [[36 33 34]
  [36 33 34]
  [36 33 34]
  ..., 
  [24 20 23]
  [27 23 26]
  [29 25 28]]

 [[

[[[76 80 82]
  [76 80 82]
  [76 80 82]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 [[70 74 76]
  [70 74 76]
  [70 74 76]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 [[63 67 69]
  [63 67 69]
  [63 67 69]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [27 30 28]
  [30 33 31]
  [31 34 32]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [27 30 28]
  [30 33 31]
  [31 34 32]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [27 30 28]
  [30 33 31]
  [31 34 32]]]
[[[74 78 80]
  [74 78 80]
  [74 78 80]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 [[67 71 73]
  [67 71 73]
  [67 71 73]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 [[61 65 67]
  [61 65 67]
  [61 65 67]
  ..., 
  [41 41 41]
  [41 41 41]
  [41 41 41]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [27 30 28]
  [30 33 31]
  [31 34 32]]

 [[38 35 34]
  [38 35 34]
  [38 35 34]
  ..., 
  [27 30 28]
  [30 33 31]
  [31 34 32]]

 [[38 35 34]
  [38

[[[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 [[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 [[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [36 33 32]
  ..., 
  [15 18 16]
  [16 19 17]
  [16 19 17]]

 [[38 35 34]
  [38 35 34]
  [36 33 32]
  ..., 
  [15 18 16]
  [16 19 17]
  [16 19 17]]

 [[38 35 34]
  [38 35 34]
  [36 33 32]
  ..., 
  [15 18 16]
  [16 19 17]
  [16 19 17]]]
[[[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 [[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 [[86 90 92]
  [86 90 92]
  [86 90 92]
  ..., 
  [48 48 48]
  [51 51 51]
  [52 52 52]]

 ..., 
 [[38 35 34]
  [38 35 34]
  [36 33 32]
  ..., 
  [15 18 16]
  [16 19 17]
  [16 19 17]]

 [[38 35 34]
  [38 35 34]
  [36 33 32]
  ..., 
  [15 18 16]
  [16 19 17]
  [16 19 17]]

 [[38 35 34]
  [38

  [10 13 11]]]
[[[62 66 68]
  [62 66 68]
  [61 65 67]
  ..., 
  [53 53 53]
  [44 44 44]
  [32 32 32]]

 [[56 60 62]
  [56 60 62]
  [56 60 62]
  ..., 
  [53 53 53]
  [45 45 45]
  [37 37 37]]

 [[57 61 63]
  [57 61 63]
  [57 61 63]
  ..., 
  [52 52 52]
  [51 51 51]
  [46 46 46]]

 ..., 
 [[18 15 14]
  [18 15 14]
  [18 15 14]
  ..., 
  [10 13 11]
  [10 13 11]
  [10 13 11]]

 [[18 15 14]
  [18 15 14]
  [18 15 14]
  ..., 
  [10 13 11]
  [10 13 11]
  [10 13 11]]

 [[18 15 14]
  [18 15 14]
  [18 15 14]
  ..., 
  [10 13 11]
  [10 13 11]
  [10 13 11]]]
[[[62 66 68]
  [62 66 68]
  [61 65 67]
  ..., 
  [52 52 52]
  [51 51 51]
  [46 46 46]]

 [[56 60 62]
  [56 60 62]
  [56 60 62]
  ..., 
  [53 53 53]
  [57 57 57]
  [60 60 60]]

 [[57 61 63]
  [57 61 63]
  [57 61 63]
  ..., 
  [52 52 52]
  [64 64 64]
  [73 73 73]]

 ..., 
 [[18 15 14]
  [18 15 14]
  [18 15 14]
  ..., 
  [10 13 11]
  [10 13 11]
  [10 13 11]]

 [[18 15 14]
  [18 15 14]
  [18 15 14]
  ..., 
  [10 13 11]
  [10 13 11]
  [10 13 11]]

 [[

  [16 16 16]]]
[[[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 [[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 [[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 ..., 
 [[32 29 28]
  [29 26 25]
  [29 26 25]
  ..., 
  [23 23 23]
  [17 17 17]
  [16 16 16]]

 [[29 26 25]
  [27 24 23]
  [28 25 24]
  ..., 
  [23 23 23]
  [17 17 17]
  [16 16 16]]

 [[28 25 24]
  [26 23 22]
  [27 24 23]
  ..., 
  [23 23 23]
  [17 17 17]
  [16 16 16]]]
[[[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 [[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 [[90 94 96]
  [90 94 96]
  [90 94 96]
  ..., 
  [43 40 41]
  [49 46 47]
  [56 53 54]]

 ..., 
 [[33 30 29]
  [32 29 28]
  [31 28 27]
  ..., 
  [23 23 23]
  [17 17 17]
  [16 16 16]]

 [[31 28 27]
  [29 26 25]
  [28 25 24]
  ..., 
  [23 23 23]
  [17 17 17]
  [16 16 16]]

 [[

  [ 26  26  26]]]
[[[138 141 146]
  [124 127 132]
  [ 99 102 107]
  ..., 
  [ 48  45  44]
  [ 67  64  63]
  [ 80  77  76]]

 [[130 133 138]
  [117 120 125]
  [ 96  99 104]
  ..., 
  [ 48  45  44]
  [ 67  64  63]
  [ 80  77  76]]

 [[111 114 119]
  [102 105 110]
  [ 90  93  98]
  ..., 
  [ 48  45  44]
  [ 66  63  62]
  [ 80  77  76]]

 ..., 
 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ..., 
  [ 34  34  34]
  [ 32  32  32]
  [ 26  26  26]]

 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ..., 
  [ 33  33  33]
  [ 32  32  32]
  [ 26  26  26]]

 [[ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]
  ..., 
  [ 33  33  33]
  [ 32  32  32]
  [ 26  26  26]]]
[[[127 130 135]
  [109 112 117]
  [ 88  91  96]
  ..., 
  [ 48  45  44]
  [ 67  64  63]
  [ 80  77  76]]

 [[114 117 122]
  [100 103 108]
  [ 85  88  93]
  ..., 
  [ 48  45  44]
  [ 67  64  63]
  [ 80  77  76]]

 [[ 97 100 105]
  [ 90  93  98]
  [ 84  87  92]
  ..., 
  [ 48  45  44]
  [ 66  63  62]
  [ 80  77  76]]

 ..., 
 [[ 36  36  36

  [240 237 238]]]
[[[163 165 167]
  [163 165 167]
  [163 165 167]
  ..., 
  [146 149 147]
  [146 149 147]
  [146 149 147]]

 [[163 165 167]
  [163 165 167]
  [163 165 167]
  ..., 
  [146 149 147]
  [146 149 147]
  [146 149 147]]

 [[163 165 167]
  [163 165 167]
  [163 165 167]
  ..., 
  [146 149 147]
  [146 149 147]
  [146 149 147]]

 ..., 
 [[215 208 205]
  [216 209 206]
  [220 213 210]
  ..., 
  [229 224 225]
  [229 224 225]
  [229 224 225]]

 [[215 208 205]
  [216 209 206]
  [220 213 210]
  ..., 
  [229 224 225]
  [229 224 225]
  [229 224 225]]

 [[215 208 205]
  [216 209 206]
  [220 213 210]
  ..., 
  [229 224 225]
  [229 224 225]
  [229 224 225]]]
[[[100 100 107]
  [106 106 113]
  [113 113 120]
  ..., 
  [ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]]

 [[101 101 108]
  [107 107 114]
  [115 115 122]
  ..., 
  [ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]]

 [[105 105 112]
  [109 109 116]
  [118 118 125]
  ..., 
  [ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]]

 ..., 
 [[ 34  34  34

[[[ 76  74  79]
  [ 79  77  82]
  [ 83  81  86]
  ..., 
  [ 53  53  53]
  [ 78  78  78]
  [ 87  87  87]]

 [[ 93  91  96]
  [ 94  92  97]
  [ 95  93  98]
  ..., 
  [ 53  53  53]
  [ 78  78  78]
  [ 87  87  87]]

 [[101  99 104]
  [102 100 105]
  [104 102 107]
  ..., 
  [ 50  50  50]
  [ 72  72  72]
  [ 79  79  79]]

 ..., 
 [[ 22  22  22]
  [ 22  22  22]
  [ 22  22  22]
  ..., 
  [ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]]

 [[ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]
  ..., 
  [ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]]

 [[ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]
  ..., 
  [ 32  32  32]
  [ 32  32  32]
  [ 32  32  32]]]
[[[ 76  74  79]
  [ 79  77  82]
  [ 83  81  86]
  ..., 
  [ 53  53  53]
  [ 78  78  78]
  [ 87  87  87]]

 [[ 93  91  96]
  [ 94  92  97]
  [ 95  93  98]
  ..., 
  [ 53  53  53]
  [ 78  78  78]
  [ 87  87  87]]

 [[101  99 104]
  [102 100 105]
  [104 102 107]
  ..., 
  [ 50  50  50]
  [ 72  72  72]
  [ 79  79  79]]

 ..., 
 [[ 22  22  22]
  [ 22  22  22]


  [33 30 29]]]
[[[62 65 70]
  [64 67 72]
  [67 70 75]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 [[62 65 70]
  [64 67 72]
  [67 70 75]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 [[62 65 70]
  [64 67 72]
  [68 71 76]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 ..., 
 [[29 29 29]
  [29 29 29]
  [29 29 29]
  ..., 
  [34 31 30]
  [34 31 30]
  [34 31 30]]

 [[29 29 29]
  [29 29 29]
  [29 29 29]
  ..., 
  [33 30 29]
  [33 30 29]
  [33 30 29]]

 [[27 27 27]
  [27 27 27]
  [27 27 27]
  ..., 
  [33 30 29]
  [33 30 29]
  [33 30 29]]]
[[[62 65 70]
  [64 67 72]
  [67 70 75]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 [[62 65 70]
  [64 67 72]
  [67 70 75]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 [[63 66 71]
  [66 69 74]
  [71 74 79]
  ..., 
  [42 39 38]
  [46 43 42]
  [48 45 44]]

 ..., 
 [[29 29 29]
  [29 29 29]
  [29 29 29]
  ..., 
  [34 31 30]
  [34 31 30]
  [34 31 30]]

 [[29 29 29]
  [29 29 29]
  [29 29 29]
  ..., 
  [33 30 29]
  [33 30 29]
  [33 30 29]]

 [[

[[[55 58 63]
  [56 59 64]
  [60 63 68]
  ..., 
  [31 28 27]
  [40 37 36]
  [61 58 57]]

 [[66 69 74]
  [67 70 75]
  [70 73 78]
  ..., 
  [31 28 27]
  [40 37 36]
  [61 58 57]]

 [[76 79 84]
  [77 80 85]
  [81 84 89]
  ..., 
  [34 31 30]
  [43 40 39]
  [63 60 59]]

 ..., 
 [[20 20 18]
  [20 20 18]
  [20 20 18]
  ..., 
  [33 30 31]
  [33 30 31]
  [33 30 31]]

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ..., 
  [33 30 31]
  [33 30 31]
  [33 30 31]]

 [[18 18 18]
  [18 18 18]
  [18 18 18]
  ..., 
  [33 30 31]
  [33 30 31]
  [33 30 31]]]
[[[55 58 63]
  [56 59 64]
  [60 63 68]
  ..., 
  [31 28 27]
  [40 37 36]
  [61 58 57]]

 [[55 58 63]
  [56 59 64]
  [60 63 68]
  ..., 
  [31 28 27]
  [40 37 36]
  [61 58 57]]

 [[66 69 74]
  [67 70 75]
  [70 73 78]
  ..., 
  [34 31 30]
  [43 40 39]
  [63 60 59]]

 ..., 
 [[20 20 18]
  [20 20 18]
  [20 20 18]
  ..., 
  [33 30 31]
  [33 30 31]
  [33 30 31]]

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ..., 
  [33 30 31]
  [33 30 31]
  [33 30 31]]

 [[18 18 18]
  [18

[[[82 84 91]
  [83 85 92]
  [84 86 93]
  ..., 
  [54 51 50]
  [50 47 46]
  [41 38 37]]

 [[82 84 91]
  [83 85 92]
  [84 86 93]
  ..., 
  [56 53 52]
  [53 50 49]
  [43 40 39]]

 [[77 79 86]
  [77 79 86]
  [80 82 89]
  ..., 
  [55 52 51]
  [53 50 49]
  [47 44 43]]

 ..., 
 [[36 33 34]
  [36 33 34]
  [36 33 34]
  ..., 
  [31 34 32]
  [31 34 32]
  [27 30 28]]

 [[35 32 33]
  [35 32 33]
  [35 32 33]
  ..., 
  [30 33 31]
  [30 33 31]
  [26 29 27]]

 [[34 31 32]
  [34 31 32]
  [34 31 32]
  ..., 
  [29 32 30]
  [29 32 30]
  [24 27 25]]]
[[[82 84 91]
  [83 85 92]
  [84 86 93]
  ..., 
  [54 51 50]
  [50 47 46]
  [41 38 37]]

 [[77 79 86]
  [77 79 86]
  [80 82 89]
  ..., 
  [56 53 52]
  [53 50 49]
  [43 40 39]]

 [[66 68 75]
  [67 69 76]
  [69 71 78]
  ..., 
  [55 52 51]
  [53 50 49]
  [47 44 43]]

 ..., 
 [[36 33 34]
  [36 33 34]
  [36 33 34]
  ..., 
  [31 34 32]
  [31 34 32]
  [27 30 28]]

 [[35 32 33]
  [35 32 33]
  [35 32 33]
  ..., 
  [30 33 31]
  [30 33 31]
  [26 29 27]]

 [[34 31 32]
  [34

  [29 33 28]]]
[[[93 90 97]
  [93 90 97]
  [93 90 97]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 [[89 86 93]
  [89 86 93]
  [89 86 93]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 [[81 78 85]
  [81 78 85]
  [81 78 85]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 ..., 
 [[34 31 32]
  [34 31 32]
  [34 31 32]
  ..., 
  [30 34 29]
  [31 35 30]
  [31 35 30]]

 [[32 29 30]
  [32 29 30]
  [32 29 30]
  ..., 
  [29 33 28]
  [30 34 29]
  [30 34 29]]

 [[31 28 29]
  [31 28 29]
  [31 28 29]
  ..., 
  [28 32 27]
  [29 33 28]
  [29 33 28]]]
[[[93 90 97]
  [93 90 97]
  [93 90 97]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 [[89 86 93]
  [89 86 93]
  [89 86 93]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 [[81 78 85]
  [81 78 85]
  [81 78 85]
  ..., 
  [38 36 32]
  [45 43 39]
  [53 51 47]]

 ..., 
 [[34 31 32]
  [34 31 32]
  [34 31 32]
  ..., 
  [30 34 29]
  [31 35 30]
  [31 35 30]]

 [[32 29 30]
  [32 29 30]
  [32 29 30]
  ..., 
  [29 33 28]
  [30 34 29]
  [30 34 29]]

 [[

  [33 33 33]]]
[[[146 149 154]
  [138 141 146]
  [125 128 133]
  ..., 
  [ 43  40  39]
  [ 56  53  52]
  [ 73  70  69]]

 [[132 135 140]
  [125 128 133]
  [114 117 122]
  ..., 
  [ 43  40  39]
  [ 56  53  52]
  [ 73  70  69]]

 [[110 113 118]
  [105 108 113]
  [ 98 101 106]
  ..., 
  [ 43  40  39]
  [ 55  52  51]
  [ 69  66  65]]

 ..., 
 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 18  18  18]
  [ 18  18  18]
  [ 18  18  18]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]]
[[[125 128 133]
  [114 117 122]
  [102 105 110]
  ..., 
  [ 48  45  44]
  [ 63  60  59]
  [ 81  78  77]]

 [[105 108 113]
  [ 98 101 106]
  [ 90  93  98]
  ..., 
  [ 48  45  44]
  [ 63  60  59]
  [ 81  78  77]]

 [[ 86  89  94]
  [ 84  87  92]
  [ 83  86  91]
  ..., 
  [ 48  45  44]
  [ 62  59  58]
  [ 77  74  73]]

 ..., 
 [[ 18  18  18]
 

  [30 30 30]]]
[[[81 84 89]
  [80 83 88]
  [80 83 88]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 [[81 84 89]
  [81 84 89]
  [82 85 90]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 [[82 85 90]
  [84 87 92]
  [86 89 94]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 ..., 
 [[24 24 24]
  [29 29 29]
  [32 32 32]
  ..., 
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[24 24 24]
  [29 29 29]
  [32 32 32]
  ..., 
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[24 24 24]
  [29 29 29]
  [32 32 32]
  ..., 
  [30 30 30]
  [30 30 30]
  [30 30 30]]]
[[[81 84 89]
  [80 83 88]
  [80 83 88]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 [[81 84 89]
  [81 84 89]
  [82 85 90]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 [[82 85 90]
  [84 87 92]
  [86 89 94]
  ..., 
  [44 44 42]
  [51 51 49]
  [55 55 53]]

 ..., 
 [[24 24 24]
  [29 29 29]
  [32 32 32]
  ..., 
  [26 26 26]
  [18 18 18]
  [13 13 13]]

 [[24 24 24]
  [29 29 29]
  [32 32 32]
  ..., 
  [25 25 25]
  [17 17 17]
  [12 12 12]]

 [[

[[[153 156 161]
  [141 144 149]
  [127 130 135]
  ..., 
  [ 46  46  44]
  [ 53  53  51]
  [ 59  59  57]]

 [[144 147 152]
  [120 123 128]
  [100 103 108]
  ..., 
  [ 46  46  44]
  [ 53  53  51]
  [ 59  59  57]]

 [[123 126 131]
  [ 99 102 107]
  [ 81  84  89]
  ..., 
  [ 46  46  44]
  [ 53  53  51]
  [ 59  59  57]]

 ..., 
 [[ 12  11  13]
  [ 12  11  13]
  [ 12  11  13]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 12  11  13]
  [ 12  11  13]
  [ 12  11  13]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 12  11  13]
  [ 12  11  13]
  [ 12  11  13]
  ..., 
  [ 33  33  33]
  [ 33  33  33]
  [ 33  33  33]]]
[[[140 143 148]
  [123 126 131]
  [107 110 115]
  ..., 
  [ 50  50  48]
  [ 59  59  57]
  [ 66  66  64]]

 [[121 124 129]
  [100 103 108]
  [ 88  91  96]
  ..., 
  [ 50  50  48]
  [ 59  59  57]
  [ 66  66  64]]

 [[103 106 111]
  [ 86  89  94]
  [ 80  83  88]
  ..., 
  [ 50  50  48]
  [ 59  59  57]
  [ 66  66  64]]

 ..., 
 [[ 13  12  14]
  [ 13  12  14]


[[[121 121 121]
  [123 123 123]
  [137 137 137]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[178 178 178]
  [176 176 176]
  [182 182 182]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[244 244 244]
  [239 239 239]
  [238 238 238]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 ..., 
 [[ 15  17  19]
  [ 15  17  19]
  [ 16  18  20]
  ..., 
  [ 41  46  29]
  [ 50  57  35]
  [ 55  62  40]]

 [[ 13  15  17]
  [ 14  16  18]
  [ 15  17  19]
  ..., 
  [ 88  96  70]
  [ 97 108  74]
  [101 112  78]]

 [[ 12  14  16]
  [ 13  15  17]
  [ 14  16  18]
  ..., 
  [124 132 106]
  [136 147 113]
  [137 148 114]]]
[[[240 164  19]
  [236 160  15]
  [205 145  34]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[239 163  18]
  [236 160  15]
  [207 147  36]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[212 152  41]
  [214 154  43]
  [190 144  58]
  ..., 
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 ..., 
 [[ 15  17  19]
  [ 16  18  20]


[[[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 164  10]
  [252 163  14]
  [253 164  15]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 160  13]
  [250 161  17]
  [249 160  16]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 161  14]
  [250 161  17]
  [250 161  17]]]
[[[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 165  10]
  [253 166  11]
  [244 157  13]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255 255 255]


In [8]:
frames.shape

(1081, 240, 240, 3)